# Instruct Shiny Server to run applications as the 'shiny' user
run_as shiny;

# Define a server that listens on port from environment variable
server {
  listen ${PORT:-3838};
  
  # Define a location for the app
  location / {
    app_dir /srv/shiny-server;
    app_init_object NULL;
    app_session_timeout 0;
    
    # Log files
    app_log_file /var/log/shiny-server.log;
  }
}